name: Jekyll site CI

on:
  schedule:
  - cron: 0 2 * * *
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build & Deploy to GitHub Pages
    uses: BryanSchuetz/jekyll-deploy-gh-pages@1.0
